POST http://localhost:5195/api/Task
Content-Type: application/json

{
  "title": "test görev",
  "status": true
}

###
DELETE http://localhost:5195/api/Task/3

### 
PUT http://localhost:5195/api/Task/4

###
GET http://localhost:5195/api/Task